# Development environment

FROM node:18


# Set app directory
WORKDIR /app

# Environment variables
ENV NODE_OPTIONS=--max_old_space_size=4096
ENV PATH /app/node_modules/.bin:$PATH

# Install with legacy peer deps to resolve ESLint conflict
COPY package.json ./
COPY sync-package-lock ./
# Use --legacy-peer-deps to resolve the eslint version conflict
RUN npm install --legacy-peer-deps

# Development server
COPY src ./src
COPY public ./public
COPY .eslintrc.js ./
COPY tsconfig.json ./
COPY webpack.config.ts ./

# This is responsible of copying node_modules and package-lock.json to host machine
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

CMD [ "npm", "start" ]