FROM node:12-alpine

WORKDIR /app
ENV NODE_OPTIONS=--max_old_space_size=4096

COPY package.json ./

# Install all dependencies (dev + prod)
RUN npm install

COPY nodemon.json ./
COPY tsconfig.json ./
COPY src ./src

RUN npm run build

COPY database ./database

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "npm", "run", "serve" ]
