# Remove the version line as Docker Compose suggests
services:
  database:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: psswd
    volumes:
      # Enhanced volume configuration for BMI data persistence
      - database-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "2345:5432"
    expose:
      - '2345'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped
    build:
      context: ../backend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      DATABASE_HOST: 'database'
      DATABASE_NAME: 'db'
      DATABASE_USER: 'admin'
      DATABASE_PASSWORD: 'psswd'
      DATABASE_PORT: '5432'
      NODE_ENV: development
      JWT_SECRET: 87e3459aec28ec448228d4f990e80f14657daefc7f01a7146e1149663b30719d
      REFRESH_JWT_SECRET: 6c2723ab022250723988e5cf38e90908be10e82ee2ce802747d279f4dd7bc823
    volumes:
      - "../backend/node_modules:/app/node_modules_for_local_development"
      - "../backend/sync-package-lock:/app/sync-package-lock"
      - "../backend/src:/app/src"
      - "../backend/public:/app/public"
      # Enhanced volume for BMI data uploads and file storage
      - "backend-uploads:/app/uploads"
      - "bmi-data:/app/bmi-data"
      # Volume for test results
      - "test-results:/app/coverage"
    ports:
      - "3000:3000"
    command: "npm run develop"

  frontend:
    depends_on:
      - backend
    restart: unless-stopped
    build:
      context: ../frontend/
      dockerfile: Dockerfile.dev
    working_dir: /app
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3000
    volumes:
      - "../frontend/node_modules:/app/node_modules_for_local_development"
      - "../frontend/sync-package-lock:/app/sync-package-lock"
      - "../frontend/src:/app/src"
    ports:
      - "3010:3010"
    command: "npm run develop"

volumes:
  database-data:
    driver: local
  backend-uploads:
    driver: local
  # New volume for BMI data storage - STAGE 1 REQUIREMENT
  bmi-data:
    driver: local
  # Volume for test results - STAGE 1 REQUIREMENT  
  test-results:
    driver: local