name: Docker Build and Push

on: 
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-backend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-backend:${{ github.sha }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile.prod
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-frontend:${{ github.sha }}

      # Optional: Build database if needed
      - name: Build and Push Database
        uses: docker/build-push-action@v5
        with:
          context: ./docker/database
          file: ./docker/database/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-database:${{ github.sha }}
        # Only run if database Dockerfile exists
        if: hashFiles('./docker/database/Dockerfile') != ''

      # Optional: Build PostgreSQL + pgAdmin (only if self-hosting)
      - name: Build and Push Database
        uses: docker/build-push-action@v5
        with:
          context: ./database
          file: ./database/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/app-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/app-database:${{ github.sha }}
        # Only run if you have a custom database setup
        if: hashFiles('./database/Dockerfile') != ''